### ISSUE TITLE
Decide on working group name and acronym

### ISSUE THREAD

**Issue by DavidSchinazi** [DavidSchinazi/ssh-charter#1]
So far we've been using the <[ssh@ietf.org](mailto:ssh@ietf.org)> mailing list. The most obvious choice would be to name the new working group `Secure Shell` and use the acronym `SSH`.

However, we have an acronym conflict. `SSH` was used for the `Site Security Handbook` WG which was active between 1994 and 1999 (see [charter](https://datatracker.ietf.org/wg/ssh/about/)). The previous iteration of a `Secure Shell` WG used the acronym `SECSH` and was active from 1997 to 2006 (see [charter](https://datatracker.ietf.org/wg/secsh/about/)).

So we might need to pick a new acronym.

**Comment by job** [comment]
`SSHM` seems available, **Secure Shell Maintenance**

**Comment by DavidSchinazi** [comment]
I think I prefer not having the word "Maintenance" in the WG name, but I don't feel overly strongly about it

**Comment by yaroslavros** [comment]
I suggest dropping "Maintenance" in the WG name. In future once "catch up" with current SSH practices is complete working group might want to keep developing SSH further (subject to rechartering). Or explore operational aspects of SSH.
If we may use historic `Secure Shell` WG name, `shell` could be an acceptable "acronym". After all, SSH is the only shell that matters, isn't it.

**Comment by job** [comment]
At that point you’d probably close the working group (because charter has been completed); or change the name as part of rechartering process. “chatch up” probably is a multi-year endeavour anyway

**Comment by richsalz** [comment]
It is really bad when the mailing list name does not match the WG name (see the spasm/lamps difference as an example).  It is also bad when people want to find the group and can't, especially when this will hopefully be of interest to a larger non-IETF community.

When the Sec AD's started to use the "ssh@ietf.org" mailing list they flushed some pending messages from the old site security handbook.  Nice archeology on the Handbook WG, which apparently concluded with nothing accomplished, and the archive site no longer exists.

  Just use ssh.

**Comment by job** [comment]
“Really bad” seems somewhat subjective. I think it’s helpful to differentiate the group of people from the protocol. Successful examples:

SIDROPS -> RPKI
IDR -> BGP
DNSOPS -> DNS

**Comment by richsalz** [comment]
True, I am speaking only about the one WG that I'm intimately involved with.  In your list, is that WG->email?  Good to know counter-examples exist.

**Comment by job** [comment]
> True, I am speaking only about the one WG that I'm intimately involved with. In your list, is that WG->email? Good to know counter-examples exist.

WG -> protocol they govern / maintain

**Comment by richsalz** [comment]
> WG -> protocol they govern / maintain

I was concerned about wgname/mailing list mismatch primarily, which would be an issue if we kept the "ssh" mailing list, but the WG name was something else. If we don't name the WG ssh, then we should really have the mailing list name be the same as the WG name.

**Comment by job** [comment]
I’m not sure it’s that big of a deal, but I hear you have a strong preference to align names a certain way.

I prefer to name the working group a bit different from the protocol, because otherwise the acronym SSH will be repeated endlessly in sentences.

**Comment by richsalz** [comment]
It's not that strong, I just failed to make myself understood.  As long as the mailing list name matches the WG name, I'll be fine :)

**Comment by debcooley** [comment]
There are examples of 'maintenance' being used in the name of working groups - ipsecme, mailmaint.  In the case of ipsec, there is new work in addition to true maintenance work.  Originally, I didn't really like the addition here, but it is growing on me.  

With respect to the mailing list name - working group name, I think ssh@ietf.org and sshm as the name of the working group is 'close enough'.   [changing the name of the email list is hard - involves yet another shift of proponents to yet another list - I'd rather not do that]  

charter:  I'll reiterate that charters can (and should) be updated as work moves forward.  There is no reason to put every wish into this initial charter.  The goal here is to establish some initial work items, establish a decent, respectful working group, and then add additional work items that might harder to build consensus.

**Comment by francoismichel** [comment]
SSHM seems to fit well the current charter.
SSHBIS is another possibility if we don't want the "maintenance" aspect, that also works well with the mailing list name. But I feel the current goal here is really about maintenance and cleanup.

**Comment by yaroslavros** [comment]
Mailing list matching acronym always helps.

Another option is to call it `sshme` and get sshme@ as the mailing list (`SSH Maintenance and Extensions`). Consistency with `ipsecme` which is on a similar mission for IPSec is not a bad thing. After all, they also resumed work of a concluded working group.

**Comment by debcooley** [comment]
@yaroslavros we aren't changing the mailing list name (with my AD hat squarely on my head).  For reasons I outline above.

I would argue that sshm and sshme are 'close enough'.

**Comment by DavidSchinazi** [comment]
Fixed via #8
