### ISSUE TITLE
Reverse first and second items

### ISSUE THREAD

**Issue by richsalz** [DavidSchinazi/ssh-charter#4]
I think the first item (document the protocol) and the second (update the crypto) need to be reversed.  We can make everyone "safer" by removing outdated protocols, establishing modern registries if needed, and recognizing what is already done in the field.

**Comment by job** [comment]
How about expressing this ordering via milestones and due dates?

**Comment by richsalz** [comment]
> How about expressing this ordering via milestones and due dates?

I dislike the cognitive dissonance/confusion that will arise and would prefer the charter list things in same order as the milestones.

**Comment by debcooley** [comment]
I think we can make this less objectionable by removing the 'first' and 'second' from the goals.  I'd rather see a bullet list for work items anyway (vice full paragraphs).  I'll think about this and make a PR, then you can see what you think....

**Comment by DavidSchinazi** [comment]
That sounds good @debcooley. That reminds me we also need to add milestones to this charter :-)

**Comment by debcooley** [comment]
I made a PR, I think this will allow the milestones to fall out more naturally.  See what you think.  I'm happy for comments/corrections whatever.
